### ISSUE TITLE
Problem deploying the certs

### ISSUE THREAD

**Issue by jasgggit** [JimDunphy/deploy-zimbra-letsencrypt.sh#10]
Hello, today I've tried to install some new certs on my Zimbra 9, using your script, but I'm getting this error now:

** Verifying 'mail.domain.eu.cer' against 'mail.domain.eu.key'
Certificate 'mail.doamin.eu.cer' and private key 'mail.gastao.eu.key' match.
** Verifying 'mail.domain.eu.cer' against 'fullchain.cer'
ERROR: Unable to validate certificate chain: C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
error 2 at 2 depth lookup: unable to get issuer certificate
error mail.domain.eu.cer: verification failed

It seems that it's not concatenating the certs ...

BTW, the last time the OLD script run without problems on 1 Oct.
Also, .acme.sh asked to use the 'zeroSSL' and to update my account, which I did.

Regards and thank you.
JG

**Comment by JimDunphy** [comment]
The script is for letsencrypt and not zerossl 

Do this first;

% ./acme.sh --set-default-ca --preferred-chain "ISRG" --server letsencrypt

then re-issue your certs  and try again with latest version of the script given the new signing. 

Jim

**Comment by jasgggit** [comment]
Hello Jim and thank you for the support.

I tried replying by email but seems not working so posting it here.

I've done the above, but still having the same issue ...

** Verifying 'mail.domain.eu.cer' against 'mail.domain.eu.key'
Certificate 'mail.domain.eu.cer' and private key 'mail.domain.eu.key' match.
** Verifying 'mail.domain.eu.cer' against 'fullchain.cer'
ERROR: Unable to validate certificate chain: C = US, O = Internet Security Research Group, CN = ISRG Root X1
error 2 at 2 depth lookup: unable to get issuer certificate
error mail.domain.eu.cer: verification failed
cert did not verify

**Comment by JimDunphy** [comment]
The cert changed that we add to the fullchain so that zimbra can verify the chain... did you use an updated version of the script or are you still using the old script that with the intermediate cert that expired on Sept 30. As a result letsencrypt signs with a new key now and we have to change what we add to that fullchain. You should see a comment that says we are grabbing the isrgrootx1.pem cert now with that deploy-letsencrypt.sh ... look for the comment that says "step 3".

Note:  ./acme.sh --list will show you if you have letsencrypt or zerossl signed certs

**Comment by jasgggit** [comment]
Hello Jim, I'm using the latest version of .acme.sh and yours.
yes, it's appended to the fullchain.cer, but does not validate. I m spending all day trying several options, but so far I can't validate the CER.
I have the LS certs, not when I opened the TTK with you.

Main_Domain     KeyLength  SAN_Domains                                                                                     CA               Created                       Renew
mail.domain.eu  ""         webmail.domain.eu,mobile.domain.eu,autodiscover.domain.eu,mail.domain2.pt,webmail.domain2.pt  LetsEncrypt.org  Thu Oct 14 14:25:16 UTC 2021  Mon Dec 13 14:25:16 UTC 2021

It seems that some 'chain' is missing, but I've downloaded all of them for LE site but still can't validate ..
Damm Zimbra ...
Thanks in advance.
JG

**Comment by JimDunphy** [comment]
Can you do this -show-chain that I talk about here:

https://forums.zimbra.org/viewtopic.php?f=15&t=60781&start=110#p301489

This is the verify that zmcertmgr is doing without the show-chain so you can work through the issues before trying that command which should help narrow down what the problem is.

Jim

**Comment by jasgggit** [comment]
Here:

zimbra@mail:/opt/letsencrypt/.acme.sh/mail.domain.eu$ openssl verify -purpose sslserver -CAfile ca.cer mail.domain.eu.cer
C = US, O = Internet Security Research Group, CN = ISRG Root X1
error 2 at 2 depth lookup: unable to get issuer certificate
error mail.domain.eu.cer: verification failed

THIS IS not a .acme.sh installed under user Zimbra.
Is an old deployment. It's installed as a non-root, and I run the deploy-lets... .sh from user zimbra.
- I used the ca.cer but using the fullchain.cer it gives the same error.

I'm trying to issue a cert for TWO domains:
domain.eu
domain2.pt

Under the same cert. That's why all this is happening now ... I need those 2 domains.

**Comment by JimDunphy** [comment]
Where is the -show-chain?  Run the above command with the show-chain:

openssl verify -show_chain -purpose sslserver -CAfile ca.cer mail.domain.eu.cer

**Comment by jasgggit** [comment]
Is the same output ::

zimbra@mail:/opt/letsencrypt/.acme.sh/mail.domain.eu$ openssl verify -show_chain -purpose sslserver -CAfile fullchain.cer mail.domain.eu.cer
C = US, O = Internet Security Research Group, CN = ISRG Root X1
error 2 at 2 depth lookup: unable to get issuer certificate
error mail.domain.eu.cer: verification failed

**Comment by jasgggit** [comment]
Ok ... so I got it right using https://whatsmychaincert.com/

Now it shows:

zimbra@mail:/opt/letsencrypt/.acme.sh/mail.domain.eu$ openssl verify -verbose -show_chain -purpose sslserver -CAfile fullchain.cer mail.domain.eu.cer
mail.domain.eu.cer: OK
Chain:
depth=0: CN = mail.domain.eu (untrusted)
depth=1: C = US, O = Let's Encrypt, CN = R3
depth=2: C = US, O = Internet Security Research Group, CN = ISRG Root X1

**Comment by JimDunphy** [comment]
You don't have the ISG_X1.pem added to that fullchain.cer from output I just saw when I did that... in the link I provided in the forum post, I explained that I used ca.cer.real in my example which has the ISRGRootX1 pem file concatenated. Do this:

% wget  "https://letsencrypt.org/certs/isrgrootx1.pem.txt" -O ISGRGRootX1.pem
% cat fullchain.cer ISGRGRootX1.pem > fullchain-ISG-X1.cer

then run that -show_chain again using fullchain-ISG-X1.cer instead of fullchain.cer and if it works, remove the -show_chain to see that it verified.

That is what the script is doing so curious unless your fullchain is corrupted to begin with and has the older chain present somehow. You should not have
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/

... anywhere in your fullchain.cer . That deploy script makes a copy of the fullchain.cer file and then adds the ISG-X1.pem to it. It then presents this to zmcertmgr which verifies it with the openssl commands you are running above. So you need to see this entry at the end of your file or it won't verify.

-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw

Because it always makes a copy from your .acme.sh directory, provided the permissions are correct for the zimbra user to read the .acme.sh ... This is why I moved to the simpler deploy option with acme.sh being owned by zimbra because some people didn't realize that .acme.sh had a permission problem for the zimbra user.  If you think this is the problem, for the user that is running the acme.sh commands... do this: chmod -R 755 ~/.acme.sh ... the goal is so that the zimbra user has read and access permission to copy all the files from ~/.acme.sh

BTW, I am trying to reproduce what you are doing.  I have an .acme.sh directory and am running the openssl commands directly. It is validating. I am not running the deploy-zimbra-letsencrypt.sh script given we can't seem to get passed validate which indicates you have the wrong chain or other. That is why I want to see the -show_chain from openssl which is how zimbra will do it. 

Jim

**Comment by jasgggit** [comment]
Hello, I isolated the issue to the fullchain.cer has somehow the cross-cer inserted to it ...
I'm aware of the permissions, and zimbra user copies well the files from the non-root usr dir ..

Using the above URL and inserting the domain cer file it generates a fullchain cer file that doesn't have the cross cert from LE ... and don't know where it comes from ...

The fullchain that is generated by the acme.sh inserts it ...

-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----

The above cert can't be on the fullchain !!

**Comment by jasgggit** [comment]
Just doing a live test, after I remove the above cert from the generated acme.sh fullchain.cer, and it's working perfectly.
Only took 24hrs to find the problem ... LOL
THANK YOU for your help and guidance.
Best regards.
JG
PS . Going to open this on the .acme.sh, something is wrong with their script.
