### ISSUE TITLE
Multiple DNS hostnames

### ISSUE THREAD

**Issue by tigre-bleu** [JimDunphy/deploy-zimbra-letsencrypt.sh#6]
My single host zimbra is hosting several domains and have DNS aliases used for imap and smtp like this:
- zimbra.domain1.com imap.domain1.com smtp.domain1.com
- zimbra.domain2.com imap.domain2.com smtp.domain2.com
- zimbra.domain3.com imap.domain3.com smtp.domain3.com

Is it necessary to generate a single certificate with all 6 FQDNs?

I would prefer having 3 certificates, 1 per domain and containing zimbra. imap. and smtp. It would be cleaner if the user looks at the certificate in his browser to have only hostnames from his own domain.

**Comment by JimDunphy** [comment]
Deploy-zimbra-letsencrypt.sh handles a single install of a certificate but you could modifiy it to suit your needs and use **zmdomaincertmgr** to do the actual install vs **zmcertmgr** I would think. See

https://wiki.zimbra.com/wiki/Multiple_SSL_Certificates,_Server_Name_Indication_(SNI)_for_HTTPS

In fact from looking at both **zmdomaincertmgr** and **zmcertmgr**, the former looks a lot cleaner to me 
but I have no idea what zimbra plans to support in the future.  My guess is zmcertmgr is probably required to support their cert zimlet from the admin interface (can do self-signed) and zmdomaincertmgr is probably a better way from the command line for PKI certs. I would think zmdomaincertmgr is newer from the way the code is structured.  **I would also be very worried about the 2 known defects still open at the bottom of the link. Specifically about IMAPS/POPS and postfix**.

acme.sh is more than capable enough to generate multiple certificates and save them in your .acme.sh directory. You would also need to update your installation script to grab these 3 certificates if you planned on using my simple script since it is currently only looking for one give a single shell script variable called domain.

The commands to deploy SNI are rather simple from the link above so I would probably just start from scratch and batch up the commands for your 3 certificates.  

Note: I prefer that newer acme.sh dns mode with the domain alias method these days for generating our certificates. See: method 2c in the recipes.  Using the automatic DNS method via one of the providers makes renewal very simple with less problems than the manual DNS mode where you hand add the TXT records to your zone files.

**Comment by tigre-bleu** [comment]
Ok, thanks for the hint, I will have a look at the documentation.

On a sidenote, it is not recommanded by acme.sh to user the certificates from the ~/.acme.sh directory as they say it is internal storage and could change in the future. You should probably use the acme.sh install command and deploy those ones.

**Comment by JimDunphy** [comment]
Thanks for the heads up.
